from django.urls import path
from .views import (
    SignupView,
    LoginView,
    GoogleAuthView,
    OTPRequestView,
    FriendListView,
    FriendInviteListView,
    FriendInviteCreateView,
    FriendInviteDecisionView,
    FriendBreakdownView,
    FriendSettlementView,
    FriendFullSettlementView,
    MongoTokenRefreshView,
    NotificationListView,
    NotificationReadAllView,
    NotificationReadView,
    ProfileUpdateView,
    PasswordChangeView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
)

urlpatterns = [
    path('signup/', SignupView.as_view()),
    path('login/', LoginView.as_view()),
    path('token/refresh/', MongoTokenRefreshView.as_view(), name='token_refresh'),
    path('google/', GoogleAuthView.as_view()),
    path('request-otp/', OTPRequestView.as_view()),
    path('profile/', ProfileUpdateView.as_view()),
    path('password/change/', PasswordChangeView.as_view()),
    path('password/reset/request/', PasswordResetRequestView.as_view()),
    path('password/reset/confirm/', PasswordResetConfirmView.as_view()),
    path('friends/', FriendListView.as_view()),
    path('friends/<str:friend_id>/ledger/', FriendBreakdownView.as_view()),
    path('friends/<str:friend_id>/settlements/', FriendSettlementView.as_view()),
    path('friends/<str:friend_id>/settlements/all/', FriendFullSettlementView.as_view()),
    path('friends/invite/', FriendInviteCreateView.as_view()),
    path('friends/invites/', FriendInviteListView.as_view()),
    path('friends/invites/<str:invite_id>/<str:action>/', FriendInviteDecisionView.as_view()),
    path('notifications/', NotificationListView.as_view()),
    path('notifications/read-all/', NotificationReadAllView.as_view()),
    path('notifications/<str:notification_id>/read/', NotificationReadView.as_view()),
]
